logging:
  level:
    com.github.aratnitsyn.gssm: error

spring:
  profiles:
    active: dev

  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: true

  jackson:
    serialization:
      indent-output: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/gssm
    username: gssm
    password: gssm
    hikari:
      pool-name: Hikari
      auto-commit: false

  jpa:
    show-sql: true

server:
  port: 8081

application:
  security:
    authentication:
      jwt:
        base64-secret: YWUyYzI1NGJlYmRiYjlmZWNmMTQ1MWYyOTk0ZGUyMmM4ODNlNWZmMzMyYTAxYjJmZWE0Yjc0MjQ5YjRkOTY3NmE0ZjFhYzc4NWE4NGNiMzg1MDNiZGQxZDIxMjQ2ZGQwNjJkNDM0OGNiNzliMzhhMGNhOTgwODZhODA1ZjUxOGQ=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
